#Study Of NumPy
##Riya Latkar
##25070123092

In [ ]:
import numpy as np

a = np.array ([1,10,20,30,40,50,500.5])
b = np.array([[1,2,3],[4,5,6]])
print(a)
print(b)
print(a.ndim)
print(b.ndim)
print(a.shape)
print(b.shape)
print(a.dtype)
print(b.dtype)

[  1.   10.   20.   30.   40.   50.  500.5]
[[1 2 3]
 [4 5 6]]
1
2
(7,)
(2, 3)
float64
int64


In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [ ]:
import numpy as np
np.linspace(0,1,4)

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [ ]:
a = np.array ([1,10,20,30,40,50,500.5])
b = np.array([[1,2,3],[4,5,6]])
print(b*2)
print(a + 5)

[[ 2  4  6]
 [ 8 10 12]]
[  6.   15.   25.   35.   45.   55.  505.5]


In [ ]:
print(np.mean(a))
print(np.median(a))
print(np.sum(a))

93.07142857142857
30.0
651.5


In [ ]:
np.max(a)

np.float64(500.5)